# -*- coding: utf-8 -*-
"""Agentic AI project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bEKabIrL4piLTGGlrxBagY94ZMKmCfQr
"""

import pandas as pd

data = [
    {"Title": "Python Developer", "Company": "TCS", "Location": "Hyderabad", "Experience": "0-2", "Salary_LPA": 5, "Remote": "No"},
    {"Title": "Senior Python Engineer", "Company": "Infosys", "Location": "Hyderabad", "Experience": "3-5", "Salary_LPA": 10, "Remote": "No"},
    {"Title": "Java Developer", "Company": "Wipro", "Location": "Bangalore", "Experience": "0-2", "Salary_LPA": 6, "Remote": "Yes"},
    {"Title": "Data Analyst", "Company": "HCL", "Location": "Chennai", "Experience": "1-3", "Salary_LPA": 7, "Remote": "No"},
    {"Title": "Backend Developer", "Company": "Startup XYZ", "Location": "Hyderabad", "Experience": "2-4", "Salary_LPA": 8, "Remote": "Yes"},
    {"Title": "Machine Learning Engineer", "Company": "Tech Mahindra", "Location": "Bangalore", "Experience": "0-2", "Salary_LPA": 9, "Remote": "No"},
    {"Title": "Frontend Developer", "Company": "Cognizant", "Location": "Mumbai", "Experience": "0-2", "Salary_LPA": 6, "Remote": "Yes"},
]

df = pd.DataFrame(data)
df

def search_jobs(role, location):
    results = df[
        (df["Title"].str.contains(role, case=False)) &
        (df["Location"].str.contains(location, case=False))
    ]
    return results

search_jobs("python", "Hyderabad")

def filter_by_salary(df, max_salary):
    return df[df["Salary_LPA"] <= max_salary]

results = search_jobs("python", "Hyderabad")
filter_by_salary(results, 8)

def filter_by_experience(df, exp_range):
    return df[df["Experience"] == exp_range]

def search_jobs(role, location):

    results = df[
        (df["Title"].str.contains(role, case=False)) &
        (df["Location"].str.contains(location, case=False))
    ]

    return results


def filter_by_salary(dataframe, max_salary):

    return dataframe[
        dataframe["Salary_LPA"] <= max_salary
    ]

role = input("Enter Job Role: ")

location = input("Enter Location: ")

try:

    max_salary = int(input("Enter Max Salary (LPA): "))

    results = search_jobs(role, location)

    results = filter_by_salary(results, max_salary)

    print("\nFiltered Results:\n")

    display(results)

except ValueError:

    print("Please enter salary as a NUMBER only.")

experience = input("Enter Experience Range (0-2 / 1-3 / 2-4 / 3-5): ")

results = filter_by_experience(results, experience)

print("Filtered Job Results:")
results

from google.colab import files

uploaded = files.upload()

!pip install pdfplumber

import pdfplumber

resume_file = list(uploaded.keys())[0]

def extract_resume_text(file):
    text = ""
    with pdfplumber.open(file) as pdf:
        for page in pdf.pages:
            if page.extract_text():
                text += page.extract_text()
    return text

resume_text = extract_resume_text(resume_file)

print("Resume successfully analyzed!\n")
print(resume_text[:500])  # preview first 500 characters

skills_list = [
    "python","java","machine learning","sql","data analysis",
    "deep learning","html","css","javascript","react",
    "pandas","numpy","tensorflow","django","flask"
]

found_skills = []

for skill in skills_list:
    if skill.lower() in resume_text.lower():
        found_skills.append(skill)

print("Skills detected in resume:")
print(found_skills)

def recommend_jobs_from_resume(skills, dataframe):

    recommendations = []

    for index, row in dataframe.iterrows():

        job_title = row["Title"].lower()

        match_score = 0

        for skill in skills:
            if skill in job_title:
                match_score += 1

        if match_score > 0:
            recommendations.append((row["Company"], row["Title"], match_score))

    return sorted(recommendations, key=lambda x: x[2], reverse=True)


recommendations = recommend_jobs_from_resume(found_skills, df)

print("\nRecommended Jobs Based on Your Resume:\n")

for company, role, score in recommendations[:5]:
    print(f"Company: {company} | Role: {role} | Match Score: {score}")

best_match = recommendations[0]

print("\nBest Job Match For You:\n")
print("Company:", best_match[0])
print("Role:", best_match[1])

def recommend_jobs_from_resume(skills, dataframe):

    recommendations = []

    for index, row in dataframe.iterrows():

        job_title = row["Title"].lower()

        match_score = 0

        for skill in skills:

            if skill.lower() in job_title:
                match_score += 1

        recommendations.append({
            "Company": row["Company"],
            "Title": row["Title"],
            "Location": row["Location"],
            "Match_Score": match_score
        })

    recommendations_df = pd.DataFrame(recommendations)

    return recommendations_df.sort_values(
        by="Match_Score",
        ascending=False
    )

recommended_jobs = recommend_jobs_from_resume(
    found_skills,
    df
)

recommended_jobs

def ats_score(found_skills, total_skills):

    if len(total_skills) == 0:
        return 0

    score = (
        len(found_skills) / len(total_skills)
    ) * 100

    return round(score, 2)

skills = [
    "Python",
    "Java",
    "SQL",
    "Machine Learning",
    "HTML",
    "CSS",
    "JavaScript"
]

score = ats_score(found_skills, skills)

print(f"ATS Resume Score: {score} / 100")

missing_skills = list(set(skills) - set(found_skills))

print("Skills you should add:")
print(missing_skills)

top_jobs = recommended_jobs.head(3)

print("Top Recommended Jobs:")
top_jobs

!pip install matplotlib

import matplotlib.pyplot as plt

plt.bar(df["Title"], df["Salary_LPA"])
plt.xticks(rotation=60)
plt.ylabel("Salary (LPA)")
plt.title("Job Salary Distribution")
plt.show()

def filter_remote(dataframe, remote):
    return dataframe[dataframe["Remote"].str.lower() == remote.lower()]

# Ask user for remote preference
remote_option = input("Remote job? (Yes/No): ")

# Show results before filtering
print("\nResults before Remote Filter:")
print(results)

# Apply remote filter
results = filter_remote(results, remote_option)

# Show final results
print("\nFiltered Results:")
if results.empty:
    print("No jobs found matching your criteria.")
else:
    print(results)

applied_jobs = []

while True:
    job = input("Enter job title you applied for (type 'stop' to finish): ")

    if job.lower() == "stop":
        break

    applied_jobs.append(job)

print("\nApplied Jobs:")
print(applied_jobs)

df["Location"].value_counts().plot(kind="bar")
plt.title("Jobs by Location")
plt.show()

!pip install spacy
!python -m spacy download en_core_web_sm

import spacy

nlp = spacy.load("en_core_web_sm")

skills_db = [
    "python", "java", "sql", "machine learning",
    "data analysis", "html", "css", "javascript"
]

def extract_skills_nlp(text):
    doc = nlp(text.lower())

    extracted = set()

    for token in doc:
        for skill in skills_db:
            if skill in token.text:
                extracted.add(skill)

    for chunk in doc.noun_chunks:
        if chunk.text in skills_db:
            extracted.add(chunk.text)

    return list(extracted)

found_skills = extract_skills_nlp(resume_text)

print(found_skills)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

df["combined_text"] = df["Title"] + " " + df["Location"]

documents = list(df["combined_text"])
documents.append(resume_text)

vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(documents)

similarity = cosine_similarity(tfidf_matrix[-1], tfidf_matrix[:-1])

scores = similarity.flatten()

df["Similarity_Score"] = scores

recommended_jobs = df.sort_values(
    by="Similarity_Score",
    ascending=False
)

recommended_jobs.head()